# Dockerfile, construir un imagen de Docker para mariadb
FROM alpine:3.17

#expone el puerto 3306
EXPOSE 3306

# Ejecuta una serie de comandos dentro del contenedor Alpine:
RUN apk update && apk upgrade && apk --no-cache add mariadb mariadb-client mariadb-common && \
    mkdir -p /run/mysqld && mkdir -p /var/lib/mysql && chown -R mysql:mysql /run/mysqld /var/lib/mysql

COPY /conf/my.cnf /etc/mysql/my.cnf
COPY ./tools/run.sh /tmp/run.sh
RUN chmod +x /tmp/run.sh

# Establece el comando predeterminado que se ejecutará cuando se inicie el contenedor
CMD ["sh", "/tmp/run.sh"]