version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - /home/hcarrasc/Desktop/inception/srcs/requirements/mariadb/tools/data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /home/hcarrasc/Desktop/inception/srcs/requirements/wordpress/tools/data:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    restart: always
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - /home/hcarrasc/Desktop/inception/srcs/requirements/wordpress/tools/data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env

networks:
  inception_network:
    driver: bridge